#!/bin/bash -x
# A script for connecting to wifi part1 
ip link set wlp2s0 up
wpa_supplicant -B -D wext -i wlp2s0 -c /etc/wpa_supplicant.conf
sleep 5
if [ "$(iw wlp2s0 link)" != "Not connected." ]; then 
	echo "Established a connection"
	sleep 1 
	echo "running dhclient wlp2s0"
	dhclient wlp2s0
	ping 8.8.8.8
else
	echo "Failed to establish connection"
fi
